name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  pinput: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # -----------------------------------------------------------------
  # INI ADALAH PERBAIKANNYA
  # -----------------------------------------------------------------
  # Kita hapus '#' dari 'assets:' dan tambahkan folder kita.
  # Pastikan 'assets:' sejajar dengan 'uses-material-design: true'
  assets:
    # Pastikan baris ini menjorok 2 spasi
    - assets/images/
  # -----------------------------------------------------------------
  
  # Bagian font biarkan saja di-comment
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
